"""initial schema

Revision ID: 3f6f955b87bb
Revises:
Create Date: 2026-08-05 18:45:49.344305

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f6f955b87bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("username_normalized", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("password_changed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'user')", name="ck_users_role"),
        sa.CheckConstraint("token_version > 0", name="ck_users_token_version_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username_normalized", name="uq_users_username_normalized"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_active_role", ["is_active", "role"], unique=False)

    op.create_table(
        "export_jobs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("record_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('processing', 'succeeded', 'failed', 'expired')",
            name="ck_export_jobs_status",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("export_jobs", schema=None) as batch_op:
        batch_op.create_index("ix_export_jobs_expiry", ["status", "expires_at"], unique=False)
    # Expression-based (DESC) index: batch_alter_table's create_index is typed
    # for plain string column names only, so this uses the module-level op
    # directly (documented to accept `text()` for functional/DESC indexes).
    op.create_index(
        "ix_export_jobs_user_created",
        "export_jobs",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
    )

    op.create_table(
        "report_templates",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=100), server_default="日报模板", nullable=False),
        sa.Column("current_version_no", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_version_no > 0", name="ck_report_templates_current_version_positive"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_report_templates_user_id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("auto_archive_on_submit", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Shanghai", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "weekly_reports",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("week_end", sa.Date(), nullable=False),
        sa.Column("generated_content_json", sa.Text(), nullable=False),
        sa.Column("content_json", sa.Text(), nullable=False),
        sa.Column("source_snapshot_json", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "week_start", name="uq_weekly_reports_user_week"),
    )
    op.create_index(
        "ix_weekly_reports_user_week",
        "weekly_reports",
        ["user_id", sa.text("week_start DESC"), sa.text("id DESC")],
        unique=False,
    )

    op.create_table(
        "template_versions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("template_id", sa.String(length=26), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("fields_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("version_no > 0", name="ck_template_versions_version_no_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["template_id"], ["report_templates.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "template_id", "version_no", name="uq_template_versions_template_version"
        ),
    )
    op.create_table(
        "daily_reports",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("template_version_id", sa.String(length=26), nullable=False),
        sa.Column("template_snapshot_json", sa.Text(), nullable=False),
        sa.Column("content_json", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status != 'draft' OR archived_at IS NULL) AND "
            "(status != 'archived' OR (submitted_at IS NOT NULL AND archived_at IS NOT NULL))",
            name="ck_daily_reports_status_timestamps",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'archived')", name="ck_daily_reports_status"
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["template_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "work_date", name="uq_daily_reports_user_work_date"),
    )
    op.create_index(
        "ix_daily_reports_user_date",
        "daily_reports",
        ["user_id", sa.text("work_date DESC"), sa.text("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_daily_reports_user_status_date",
        "daily_reports",
        ["user_id", "status", sa.text("work_date DESC")],
        unique=False,
    )

    op.create_table(
        "weekly_report_sources",
        sa.Column("weekly_report_id", sa.String(length=26), nullable=False),
        sa.Column("daily_report_id", sa.String(length=26), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("included_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["daily_report_id"], ["daily_reports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["weekly_report_id"], ["weekly_reports.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("weekly_report_id", "daily_report_id"),
    )
    with op.batch_alter_table("weekly_report_sources", schema=None) as batch_op:
        batch_op.create_index("ix_weekly_sources_daily", ["daily_report_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weekly_report_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_weekly_sources_daily")

    op.drop_table("weekly_report_sources")
    with op.batch_alter_table("daily_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_daily_reports_user_status_date")
        batch_op.drop_index("ix_daily_reports_user_date")

    op.drop_table("daily_reports")
    op.drop_table("template_versions")
    with op.batch_alter_table("weekly_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_weekly_reports_user_week")

    op.drop_table("weekly_reports")
    op.drop_table("user_settings")
    op.drop_table("report_templates")
    with op.batch_alter_table("export_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_export_jobs_user_created")
        batch_op.drop_index("ix_export_jobs_expiry")

    op.drop_table("export_jobs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_active_role")

    op.drop_table("users")
    # ### end Alembic commands ###
