"""Persistent JWT signing secret.

Unlike `runtime_secret` (regenerated by Electron on every launch, and only
ever meant to gate local IPC — see architecture.md SEC-002), a 24h JWT
must keep validating across ordinary backend restarts, or every app
restart would force a fresh login. The secret is generated once and
stored next to the database in `data_dir` so it survives restarts but
never leaves this machine's data directory (never logged, never returned
by any API, never committed — matches coding-rule.md's "no hardcoded
JWT secret" rule by not hardcoding it at all).
"""

import os
import secrets
from pathlib import Path

JWT_SECRET_FILE_NAME = "jwt_secret.key"
_SECRET_BYTES = 32
_SECRET_HEX_LENGTH = _SECRET_BYTES * 2


def load_or_create_jwt_secret(data_dir: Path) -> str:
    secret_path = data_dir / JWT_SECRET_FILE_NAME
    secret = secrets.token_hex(_SECRET_BYTES)
    try:
        descriptor = os.open(secret_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        return _read_existing(secret_path)

    with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as secret_file:
        secret_file.write(secret)
        secret_file.flush()
        os.fsync(secret_file.fileno())
    return secret


def _read_existing(secret_path: Path) -> str:
    value = secret_path.read_text(encoding="utf-8").strip()
    if len(value) != _SECRET_HEX_LENGTH:
        raise RuntimeError("JWT signing secret file is invalid")
    try:
        bytes.fromhex(value)
    except ValueError as error:
        raise RuntimeError("JWT signing secret file is invalid") from error
    return value
